#!/bin/bash
# Plot router upling with `rrdtool` modified script from Cacti
# Usage: 
# cacti-plot_uplink.sh <HOUR>
#
# Sat 19 Sep 11:24:45 WIB 2020


# rrdtool complains if there are ':'
now=$(date | sed -e's/:/\\:/g')

# how many hours back to plot?
hours=$1

# in epoch seconds
#secs=$(bc -l <<< "scale=0;3600*$hours")
secs=$((3600*$hours))

end=$(date +%s)
start=$(($end-$secs))

echo -e "Creating rrdtool graph at "$now"\n\nVariables:\nhours=$hours\nsecs=$secs\nstart=$start\n__end=$end"

# Plot png with rrdtool script from cacti
plots()
{
/usr/bin/rrdtool graph - \
	--imgformat=PNG \
	--start=$start \
	--end=$end \
	--pango-markup  \
	--title='Router Traffic - Uplink to ISP' \
	--vertical-label='bits per second' \
	--slope-mode \
	--base=1000 \
	--height=200 \
	--width=700 \
	--rigid \
	--alt-autoscale-max \
	--lower-limit='0' \
	COMMENT:"Last $hours hours \c" \
	COMMENT:"Chart created\: $now \c" \
	COMMENT:"  \n" \
	--border 1 --slope-mode \
	--watermark 'Generated by Cacti' \
	DEF:a='/usr/share/cacti/site/rra/gateway_traffic_in_13.rrd':'traffic_in':MAX \
	DEF:b='/usr/share/cacti/site/rra/gateway_traffic_in_13.rrd':'traffic_in':AVERAGE \
	DEF:c='/usr/share/cacti/site/rra/gateway_traffic_in_13.rrd':'traffic_out':MAX \
	DEF:d='/usr/share/cacti/site/rra/gateway_traffic_in_13.rrd':'traffic_out':AVERAGE \
	CDEF:cdefa='a,8,*' \
	CDEF:cdefb='b,8,*' \
	CDEF:cdeff='c,8,*' \
	CDEF:cdefg='d,8,*' \
	LINE1:cdefa#00CF00FF:  \
	AREA:cdefb#00CF007F:'Inbound '  \
	GPRINT:cdefb:LAST:'Current\:%8.2lf %s'  \
	GPRINT:cdefb:AVERAGE:'Average\:%8.2lf %s'  \
	GPRINT:cdefb:MAX:'Maximum\:%8.2lf %s\n'  \
	LINE1:cdeff#002A97FF:  \
	AREA:cdefg#002A977F:'Outbound'  \
	GPRINT:cdefg:LAST:'Current\:%8.2lf %s'  \
	GPRINT:cdefg:AVERAGE:'Average\:%8.2lf %s'  \
	GPRINT:cdefg:MAX:'Maximum\:%8.2lf %s\n' > cacti-graph.png ; echo -e "done check cacti-graph.png"
}

# plot it
plots
